# GfxLib Makefile

PROCESSOR = 386 # for the 32-bit compilers
MODEL = f       # flat

CC = wcc$(PROCESSOR)
FC = wfc$(PROCESSOR)
ASM = tasm

CFLAGS = -m$(MODEL) -zq -od -d2 -zp4 -ei -W4 # debug
#CFLAGS  = -m$(MODEL) -zq -s -oxt -zp4 -ei -W4 # release
FFLAGS  = -m$(MODEL) -noterm
AFLAGS  = -mx -ml

.EXTENSIONS:
.EXTENSIONS: .exe .rex .lib .obj .wbj .asm .c .for

.BEFORE:
	@set INCLUDE=..\apodmx;.;$(%watcom)\h;
	@set LIB=$(%watcom)\lib386;$(%lib)
	@set DOS4G=QUIET

!include objdef.mif

# explicit rules

all :   gfx.lib .symbolic
	@%null

gfx.lib : $(objs)
	 %make temp.lnk
	 wlib $^@ /n /b @temp.lnk

clean : .SYMBOLIC
	del *.obj
	del *.lib

# implicit rules

temp.lnk : objdef.mif makefile
	%create $^@
	for %i in ($(objs)) do %append $^@ -+%i

.c.obj :
	$(CC) $^& $(CFLAGS)

.c.wbj :
	$(CC) $^& $(CFLAGS) -zw -fo=$^&.wbj

.for.obj :
	$(FC) $^& $(FFLAGS)

.asm.obj :
	$(ASM) $(AFLAGS) $^&;
