#ifndef STORE_H
#define STORE_H

#include "../gfx/types.h"

/***************************************************************************
STORE_Init () - Inits Store Things
 ***************************************************************************/
void STORE_Init( void );

/***************************************************************************
STORE_Enter () - Lets User go in store and buy and sell things
 ***************************************************************************/
void STORE_Enter( void );

#endif
