# Raptor Makefile

PROCESSOR = 386 # for the 32-bit compilers
MODEL = f       # flat

CC = wcc$(PROCESSOR)
FC = wfc$(PROCESSOR)
ASM = tasm

CFLAGS = -m$(MODEL) -zq -od -d2 -zp4 -ei -W4 # debug
#CFLAGS  = -m$(MODEL) -zq -s -oxt -zp4 -ei -W4 # release
FFLAGS  = -m$(MODEL) -noterm
AFLAGS  = -mx -ml

.EXTENSIONS:
.EXTENSIONS: .exe .rex .lib .obj .wbj .asm .c .for

.BEFORE:
	@set INCLUDE=.;$(%watcom)\h;
	@set LIB=..\apodmx;..\gfx;..\audiolib\AL_109;
	@set DOS4G=QUIET                      

!include objdef.mif

# explicit rules

all :   rap.exe .symbolic
	@%null

rap.exe : $(objs)
	 %make temp.lnk    
	 wlink @temp.lnk

clean : .SYMBOLIC
	del *.obj
	del *.exe

# implicit rules

temp.lnk : objdef.mif makefile
	%create $^@
	%append $^@ NAME rap
	%append $^@ DEBUG all
	%append $^@ OPT MAP=test.map
	%append $^@ OPT STACK=8192
	%append $^@ OPT CASEEXACT
	%append $^@ LIBRARY APODMX.lib
	%append $^@ LIBRARY AL_109.lib
	%append $^@ LIBRARY GFX.LIB 
	%append $^@ LIB NOEMU387.LIB 
	%append $^@ SYSTEM dos4g
	for %i in ($(objs)) do %append $^@ FILE %i

.c.obj :
	$(CC) $^& $(CFLAGS)

.c.wbj :
	$(CC) $^& $(CFLAGS) -zw -fo=$^&.wbj

.for.obj :
	$(FC) $^& $(FFLAGS)

.asm.obj :
	$(ASM) $(AFLAGS) $^&;
