#ifndef RAPTOR_H
#define RAPTOR_H

#include "../gfx/exitapi.h"
#include "../gfx/gfxapi.h"
#include "../gfx/glbapi.h"
#include "../gfx/imsapi.h"
#include "../gfx/kbdapi.h"
#include "../gfx/ptrapi.h"
#include "../gfx/swdapi.h"
#include "../gfx/tsmapi.h"
#include "../gfx/types.h"
#include "../gfx/vmemapi.h"

#include "../apodmx/dmx.h"

#define MAX_SHIELD 100
#define MAX_SUPER  100

#include "anims.h"
#include "bonus.h"
#include "enemy.h"
#include "eshot.h"
#include "flame.h"
#include "fx.h"
#include "help.h"
#include "input.h"
#include "intro.h"
#include "loadsave.h"
#include "map.h"
#include "movie.h"
#include "objects.h"
#include "public.h"
#include "shadows.h"
#include "shots.h"
#include "store.h"
#include "tile.h"
#include "windows.h"

#endif
