#ifndef STORE_H
#define STORE_H

#include "../gfx/types.h"

/***************************************************************************
STORE_Init () - Inits Store Things
 ***************************************************************************/
VOID STORE_Init( VOID );

/***************************************************************************
STORE_Enter () - Lets User go in store and buy and sell things
 ***************************************************************************/
VOID STORE_Enter( VOID );

#endif
